### ISSUE TITLE
hello , can you share the TeyeD dataset?

### ISSUE THREAD

**Issue by NotOnlyAI** [Morris88826/TEyeD#2]
thanks!!  maybe a share in baidudisk or goolgedrive?  my email is 442622355@qq.com

**Comment by dingweijie2222** [comment]
thanks, I want too.

**Comment by Morris88826** [comment]
This appears to be the same issue as https://github.com/Morris88826/TEyeD/issues/1. I really hope that I can share the dataset; however, I am also afraid of violating their property right. Maybe you can look up [here](https://www.v7labs.com/pricing) and ask for the education plan.
